# Generated by Django 3.2.13 on 2022-06-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20220614_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, help_text='Рекомендации для продукта', related_name='_catalogue_product_recommended_products_+', through='catalogue.ProductRecommendation', to='catalogue.Product', verbose_name='Recommended products'),
        ),
    ]
